// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/store_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_CREDENTIALS ItemType = 0
	ItemType_TEXT_DATA   ItemType = 1
	ItemType_BINARY_DATA ItemType = 2
	ItemType_CREDIT_CARD ItemType = 3
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "CREDENTIALS",
		1: "TEXT_DATA",
		2: "BINARY_DATA",
		3: "CREDIT_CARD",
	}
	ItemType_value = map[string]int32{
		"CREDENTIALS": 0,
		"TEXT_DATA":   1,
		"BINARY_DATA": 2,
		"CREDIT_CARD": 3,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_store_service_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_proto_store_service_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{0}
}

type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                   // guid of item
	ItemType ItemType `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3,enum=protobuf.store.service.ItemType" json:"item_type,omitempty"` // type of item
	File     string   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`                                                               // filename
	Checksum string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`                                                       // checksum of item data
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfo) GetItemType() ItemType {
	if x != nil {
		return x.ItemType
	}
	return ItemType_CREDENTIALS
}

func (x *ItemInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ItemInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type GetItemsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetItemsListRequest) Reset() {
	*x = GetItemsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListRequest) ProtoMessage() {}

func (x *GetItemsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListRequest.ProtoReflect.Descriptor instead.
func (*GetItemsListRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{1}
}

type GetItemsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemsInfo []*ItemInfo `protobuf:"bytes,1,rep,name=itemsInfo,proto3" json:"itemsInfo,omitempty"` // items info list
	Count     int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`        // size of items info list
}

func (x *GetItemsListResponse) Reset() {
	*x = GetItemsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsListResponse) ProtoMessage() {}

func (x *GetItemsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsListResponse.ProtoReflect.Descriptor instead.
func (*GetItemsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsListResponse) GetItemsInfo() []*ItemInfo {
	if x != nil {
		return x.ItemsInfo
	}
	return nil
}

func (x *GetItemsListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UploadItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                   // guid of item
	ItemType ItemType `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3,enum=protobuf.store.service.ItemType" json:"item_type,omitempty"` // type of item
	Chunk    []byte   `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`                                                             // payload
}

func (x *UploadItemRequest) Reset() {
	*x = UploadItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadItemRequest) ProtoMessage() {}

func (x *UploadItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadItemRequest.ProtoReflect.Descriptor instead.
func (*UploadItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadItemRequest) GetItemType() ItemType {
	if x != nil {
		return x.ItemType
	}
	return ItemType_CREDENTIALS
}

func (x *UploadItemRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type UploadItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`      // guid of item
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // size of received data
}

func (x *UploadItemResponse) Reset() {
	*x = UploadItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadItemResponse) ProtoMessage() {}

func (x *UploadItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadItemResponse.ProtoReflect.Descriptor instead.
func (*UploadItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{4}
}

func (x *UploadItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadItemResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"` // guid of item
}

func (x *DownloadItemRequest) Reset() {
	*x = DownloadItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadItemRequest) ProtoMessage() {}

func (x *DownloadItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadItemRequest.ProtoReflect.Descriptor instead.
func (*DownloadItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadItemRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type DownloadItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DownloadItemResponse) Reset() {
	*x = DownloadItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_store_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadItemResponse) ProtoMessage() {}

func (x *DownloadItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadItemResponse.ProtoReflect.Descriptor instead.
func (*DownloadItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_service_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadItemResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_store_service_proto protoreflect.FileDescriptor

var file_proto_store_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x3d, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22,
	0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x78, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x38,
	0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x4c, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x58, 0x54, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52,
	0x44, 0x10, 0x03, 0x32, 0xcd, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x29, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x6b, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_store_service_proto_rawDescOnce sync.Once
	file_proto_store_service_proto_rawDescData = file_proto_store_service_proto_rawDesc
)

func file_proto_store_service_proto_rawDescGZIP() []byte {
	file_proto_store_service_proto_rawDescOnce.Do(func() {
		file_proto_store_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_store_service_proto_rawDescData)
	})
	return file_proto_store_service_proto_rawDescData
}

var file_proto_store_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_store_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_store_service_proto_goTypes = []any{
	(ItemType)(0),                // 0: protobuf.store.service.ItemType
	(*ItemInfo)(nil),             // 1: protobuf.store.service.ItemInfo
	(*GetItemsListRequest)(nil),  // 2: protobuf.store.service.GetItemsListRequest
	(*GetItemsListResponse)(nil), // 3: protobuf.store.service.GetItemsListResponse
	(*UploadItemRequest)(nil),    // 4: protobuf.store.service.UploadItemRequest
	(*UploadItemResponse)(nil),   // 5: protobuf.store.service.UploadItemResponse
	(*DownloadItemRequest)(nil),  // 6: protobuf.store.service.DownloadItemRequest
	(*DownloadItemResponse)(nil), // 7: protobuf.store.service.DownloadItemResponse
}
var file_proto_store_service_proto_depIdxs = []int32{
	0, // 0: protobuf.store.service.ItemInfo.item_type:type_name -> protobuf.store.service.ItemType
	1, // 1: protobuf.store.service.GetItemsListResponse.itemsInfo:type_name -> protobuf.store.service.ItemInfo
	0, // 2: protobuf.store.service.UploadItemRequest.item_type:type_name -> protobuf.store.service.ItemType
	2, // 3: protobuf.store.service.StoreService.GetItemsList:input_type -> protobuf.store.service.GetItemsListRequest
	4, // 4: protobuf.store.service.StoreService.UploadItem:input_type -> protobuf.store.service.UploadItemRequest
	6, // 5: protobuf.store.service.StoreService.DownloadItem:input_type -> protobuf.store.service.DownloadItemRequest
	3, // 6: protobuf.store.service.StoreService.GetItemsList:output_type -> protobuf.store.service.GetItemsListResponse
	5, // 7: protobuf.store.service.StoreService.UploadItem:output_type -> protobuf.store.service.UploadItemResponse
	7, // 8: protobuf.store.service.StoreService.DownloadItem:output_type -> protobuf.store.service.DownloadItemResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_store_service_proto_init() }
func file_proto_store_service_proto_init() {
	if File_proto_store_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_store_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetItemsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetItemsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UploadItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UploadItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_store_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_store_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_store_service_proto_goTypes,
		DependencyIndexes: file_proto_store_service_proto_depIdxs,
		EnumInfos:         file_proto_store_service_proto_enumTypes,
		MessageInfos:      file_proto_store_service_proto_msgTypes,
	}.Build()
	File_proto_store_service_proto = out.File
	file_proto_store_service_proto_rawDesc = nil
	file_proto_store_service_proto_goTypes = nil
	file_proto_store_service_proto_depIdxs = nil
}
