// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/store_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_GetItemsList_FullMethodName = "/protobuf.store.service.StoreService/GetItemsList"
	StoreService_UploadItem_FullMethodName   = "/protobuf.store.service.StoreService/UploadItem"
	StoreService_DownloadItem_FullMethodName = "/protobuf.store.service.StoreService/DownloadItem"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	GetItemsList(ctx context.Context, in *GetItemsListRequest, opts ...grpc.CallOption) (*GetItemsListResponse, error)
	UploadItem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadItemRequest, UploadItemResponse], error)
	DownloadItem(ctx context.Context, in *DownloadItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadItemResponse], error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) GetItemsList(ctx context.Context, in *GetItemsListRequest, opts ...grpc.CallOption) (*GetItemsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsListResponse)
	err := c.cc.Invoke(ctx, StoreService_GetItemsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UploadItem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadItemRequest, UploadItemResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], StoreService_UploadItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadItemRequest, UploadItemResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UploadItemClient = grpc.ClientStreamingClient[UploadItemRequest, UploadItemResponse]

func (c *storeServiceClient) DownloadItem(ctx context.Context, in *DownloadItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadItemResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[1], StoreService_DownloadItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadItemRequest, DownloadItemResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_DownloadItemClient = grpc.ServerStreamingClient[DownloadItemResponse]

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
type StoreServiceServer interface {
	GetItemsList(context.Context, *GetItemsListRequest) (*GetItemsListResponse, error)
	UploadItem(grpc.ClientStreamingServer[UploadItemRequest, UploadItemResponse]) error
	DownloadItem(*DownloadItemRequest, grpc.ServerStreamingServer[DownloadItemResponse]) error
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) GetItemsList(context.Context, *GetItemsListRequest) (*GetItemsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsList not implemented")
}
func (UnimplementedStoreServiceServer) UploadItem(grpc.ClientStreamingServer[UploadItemRequest, UploadItemResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadItem not implemented")
}
func (UnimplementedStoreServiceServer) DownloadItem(*DownloadItemRequest, grpc.ServerStreamingServer[DownloadItemResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadItem not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_GetItemsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetItemsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetItemsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetItemsList(ctx, req.(*GetItemsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UploadItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).UploadItem(&grpc.GenericServerStream[UploadItemRequest, UploadItemResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UploadItemServer = grpc.ClientStreamingServer[UploadItemRequest, UploadItemResponse]

func _StoreService_DownloadItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).DownloadItem(m, &grpc.GenericServerStream[DownloadItemRequest, DownloadItemResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_DownloadItemServer = grpc.ServerStreamingServer[DownloadItemResponse]

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.store.service.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemsList",
			Handler:    _StoreService_GetItemsList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadItem",
			Handler:       _StoreService_UploadItem_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadItem",
			Handler:       _StoreService_DownloadItem_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/store_service.proto",
}
